//! Fallback discovery for Forge and NeoForge loader versions.
//!
//! Modrinth hosts a manifest (`{loader}/v{format}/manifest.json`) listing,
//! per game version, which loader builds exist and where to fetch their
//! install profile. That manifest is generated by a job on Modrinth's end
//! and can end up missing game versions it should cover (see the "26.3"-only
//! NeoForge manifest outage this was written for). When that happens the
//! per-version profile JSON (`{loader}/v{format}/versions/{id}.json`) is
//! still hosted and correct -- only the top-level index is wrong -- so this
//! module rediscovers which loader version IDs are valid for each game
//! version by asking the loader's own canonical (Maven) metadata directly,
//! and reconstructs `LoaderVersion` entries pointing at Modrinth's existing
//! per-version URLs.
//!
//! [`patch_manifest_gaps`] is the single entry point: it's called from
//! `api::metadata::get_loader_versions`, so every consumer of a loader
//! manifest -- the launch path, instance-editing UI, version pickers --
//! transparently sees the same complete, gap-filled picture.
//!
//! Fabric and Quilt aren't affected by this class of bug: their loader
//! versions aren't tied to a specific game version in the manifest (a single
//! wildcard `${modrinth.gameVersion}` entry covers every game version), so
//! there is nothing to fall back for, and this module is a no-op for them.

use std::collections::HashMap;
use std::sync::LazyLock;
use std::time::{Duration, Instant};

use daedalus::modded::{LoaderVersion, Manifest, Version as ManifestVersion};
use dashmap::DashMap;
use quick_xml::Reader;
use quick_xml::events::Event;
use reqwest::Method;

use crate::State;
use crate::data::ModLoader;
use crate::util::fetch::{fetch_advanced, fetch_json};

const NEOFORGE_MAVEN_METADATA_URL: &str = "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml";
const FORGE_MAVEN_METADATA_URL: &str = "https://files.minecraftforge.net/net/minecraftforge/forge/maven-metadata.json";

/// How long a fetched set of upstream candidates is reused before refetching.
/// This is queried far more often than Modrinth's own manifest changes (e.g.
/// once per launch, and again per settings-modal open), so a short in-memory
/// cache keeps this from hammering the upstream Maven hosts; it's separate
/// from -- and much shorter than -- the main loader-manifest cache, since its
/// only job is to avoid redundant requests within a short burst of activity.
const CACHE_TTL: Duration = Duration::from_secs(15 * 60);

type CandidatesByGameVersion = HashMap<String, Vec<LoaderVersion>>;

static CANDIDATE_CACHE: LazyLock<DashMap<ModLoader, (Instant, CandidatesByGameVersion)>> =
    LazyLock::new(DashMap::new);

/// Fills in any game versions missing from `manifest` (or present but with
/// no loader versions listed) using the loader's upstream metadata. No-op
/// for loaders this fallback doesn't cover.
pub(crate) async fn patch_manifest_gaps(
    loader: ModLoader,
    manifest: &mut Manifest,
) -> crate::Result<()> {
    let all = fetch_all_candidates_cached(loader).await?;
    if all.is_empty() {
        return Ok(());
    }

    for (game_version, mut loaders) in all {
        loaders.reverse();

        if let Some(entry) =
            manifest.game_versions.iter_mut().find(|v| v.id == game_version)
        {
            if entry.loaders.is_empty() {
                entry.loaders = loaders;
            }
        } else {
            manifest.game_versions.push(ManifestVersion {
                id: game_version,
                stable: true,
                version_group: None,
                loaders,
            });
        }
    }

    Ok(())
}

async fn fetch_all_candidates_cached(
    loader: ModLoader,
) -> crate::Result<CandidatesByGameVersion> {
    if let Some(entry) = CANDIDATE_CACHE.get(&loader)
        && entry.0.elapsed() < CACHE_TTL
    {
        return Ok(entry.1.clone());
    }

    let fresh = fetch_all_candidates(loader).await?;
    CANDIDATE_CACHE.insert(loader, (Instant::now(), fresh.clone()));
    Ok(fresh)
}

async fn fetch_all_candidates(
    loader: ModLoader,
) -> crate::Result<CandidatesByGameVersion> {
    let state = State::get().await?;

    match loader {
        ModLoader::NeoForge => fetch_neoforge_candidates(&state).await,
        ModLoader::Forge => fetch_forge_candidates(&state).await,
        ModLoader::Fabric | ModLoader::Quilt | ModLoader::Vanilla => {
            Ok(HashMap::new())
        }
    }
}

fn loader_version_url(loader: &str, id: &str) -> String {
    format!(
        "{}{loader}/v0/versions/{id}.json",
        env!("MODRINTH_LAUNCHER_META_URL"),
    )
}

async fn fetch_neoforge_candidates(
    state: &State,
) -> crate::Result<CandidatesByGameVersion> {
    let bytes = fetch_advanced(
        Method::GET,
        NEOFORGE_MAVEN_METADATA_URL,
        None,
        None,
        None,
        None,
        None,
        None,
        &state.api_semaphore,
        &state.pool,
    )
    .await?;

    let xml = String::from_utf8_lossy(&bytes);
    let versions = parse_maven_versions(&xml);

    let mut by_game_version: CandidatesByGameVersion = HashMap::new();
    for raw in versions {
        let Some(game_version) = neoforge_game_version(&raw) else {
            continue;
        };

        by_game_version.entry(game_version).or_default().push(
            LoaderVersion {
                url: loader_version_url("neo", &raw),
                id: raw,
                stable: false,
            },
        );
    }

    Ok(by_game_version)
}

/// Maps a raw NeoForge version string (e.g. `21.1.251`, `26.1.0.10-beta`) to
/// the Minecraft game version it targets, mirroring the rule the manifest
/// generator itself uses.
fn neoforge_game_version(loader_version: &str) -> Option<String> {
    let mut parts = loader_version.split('.');

    let major_or_year = parts.next()?.parse::<u32>().ok()?;
    let minor = parts.next()?;

    Some(if major_or_year >= 26 {
        // Year-based Minecraft versions (started in 2026): major.minor.hotfix.build
        let hotfix = parts.next()?;
        if hotfix == "0" {
            format!("{major_or_year}.{minor}")
        } else {
            format!("{major_or_year}.{minor}.{hotfix}")
        }
    } else if minor == "0" {
        format!("1.{major_or_year}")
    } else {
        format!("1.{major_or_year}.{minor}")
    })
}

async fn fetch_forge_candidates(
    state: &State,
) -> crate::Result<CandidatesByGameVersion> {
    let manifest = fetch_json::<HashMap<String, Vec<String>>>(
        Method::GET,
        FORGE_MAVEN_METADATA_URL,
        None,
        None,
        None,
        &state.api_semaphore,
        &state.pool,
    )
    .await?;

    Ok(manifest
        .into_iter()
        .map(|(game_version, versions)| {
            let loaders = versions
                .iter()
                .filter_map(|full_version| {
                    // Forge versions are published as
                    // `{game_version}-{loader_version}` (e.g.
                    // `1.20.1-47.4.20`); only the loader version half is
                    // used as the id Modrinth hosts per-version profiles
                    // under.
                    let id = full_version.split('-').nth(1)?.to_string();
                    Some(LoaderVersion {
                        url: loader_version_url("forge", &id),
                        id,
                        stable: false,
                    })
                })
                .collect();
            (game_version, loaders)
        })
        .collect())
}

/// Extracts the text content of every top-level Maven `<version>` element
/// from a `maven-metadata.xml` document, in document order.
fn parse_maven_versions(xml: &str) -> Vec<String> {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().enable_all_checks(false);

    let mut versions = Vec::new();
    let mut in_version = false;
    let mut buf = Vec::new();

    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(e)) if e.name().as_ref() == b"version" => {
                in_version = true;
            }
            Ok(Event::End(e)) if e.name().as_ref() == b"version" => {
                in_version = false;
            }
            Ok(Event::Text(e)) if in_version => {
                if let Ok(text) = e.xml_content() {
                    versions.push(text.into_owned());
                }
            }
            Ok(Event::Eof) => break,
            Err(_) => break,
            _ => {}
        }

        buf.clear();
    }

    versions
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_maven_versions() {
        let xml = r#"
            <metadata>
                <groupId>net.neoforged</groupId>
                <artifactId>neoforge</artifactId>
                <versioning>
                    <versions>
                        <version>21.1.1</version>
                        <version>21.1.251</version>
                        <version>26.1.0.10-beta</version>
                    </versions>
                </versioning>
            </metadata>
        "#;

        assert_eq!(
            parse_maven_versions(xml),
            vec!["21.1.1", "21.1.251", "26.1.0.10-beta"]
        );
    }

    #[test]
    fn maps_legacy_neoforge_versions() {
        assert_eq!(
            neoforge_game_version("21.1.251").as_deref(),
            Some("1.21.1")
        );
        assert_eq!(neoforge_game_version("21.0.5").as_deref(), Some("1.21"));
        assert_eq!(
            neoforge_game_version("20.2.86").as_deref(),
            Some("1.20.2")
        );
    }

    #[test]
    fn maps_year_based_neoforge_versions() {
        assert_eq!(neoforge_game_version("26.3.0.4").as_deref(), Some("26.3"));
        assert_eq!(
            neoforge_game_version("26.3.4.10").as_deref(),
            Some("26.3.4")
        );
        assert_eq!(neoforge_game_version("26.1.0.10").as_deref(), Some("26.1"));
    }
}
