//! Reads/writes the handful of `server.properties` fields a server admin
//! actually needs day to day (MOTD, difficulty, whitelist, etc.) -- not a
//! full raw-properties editor. `server.properties` is normally generated by
//! the server jar itself on first launch, using its own defaults; this
//! module writes a starter file with our own defaults right after install
//! (see `install::write_default_properties`) so these settings are editable
//! and the configured port actually takes effect on the very first launch,
//! rather than only after the server has been started once already.
//!
//! Reading/writing preserves every other line in the file byte-for-byte
//! (comments, and any key this struct doesn't manage, e.g. `level-seed`,
//! `resource-pack`, ...) -- only the managed keys' values are touched.

use super::HostedServer;
use crate::state::State;
use crate::util::io;
use serde::{Deserialize, Serialize};
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HostedServerProperties {
    pub motd: String,
    pub max_players: u32,
    /// `peaceful` | `easy` | `normal` | `hard`
    pub difficulty: String,
    /// `survival` | `creative` | `adventure` | `spectator`
    pub gamemode: String,
    pub hardcore: bool,
    pub pvp: bool,
    /// Whether Mojang session verification is required to join -- turning
    /// this off allows unauthenticated ("cracked") clients to connect.
    pub online_mode: bool,
    pub white_list: bool,
    pub enable_command_block: bool,
    pub allow_flight: bool,
    pub allow_nether: bool,
    pub spawn_protection: u32,
    pub view_distance: u32,
    pub simulation_distance: u32,
}

impl Default for HostedServerProperties {
    fn default() -> Self {
        Self {
            motd: "A Minecraft Server".to_string(),
            max_players: 20,
            difficulty: "easy".to_string(),
            gamemode: "survival".to_string(),
            hardcore: false,
            pvp: true,
            online_mode: true,
            white_list: false,
            enable_command_block: false,
            allow_flight: false,
            allow_nether: true,
            spawn_protection: 16,
            view_distance: 10,
            simulation_distance: 10,
        }
    }
}

fn properties_path(server_dir: &Path) -> std::path::PathBuf {
    server_dir.join("server.properties")
}

enum RawLine {
    /// A `key=value` entry line (not a comment).
    Entry { key: String, value: String },
    /// A comment, blank line, or anything else -- kept byte-for-byte.
    Verbatim(String),
}

/// Reads `server.properties` into `HostedServerProperties`, filling in
/// defaults for any managed key the file doesn't have (or if the file
/// doesn't exist yet -- e.g. the server hasn't been started for the first
/// time and `write_default_properties` somehow didn't run).
pub async fn get(server_id: &str, state: &State) -> crate::Result<HostedServerProperties> {
    let server_dir = state.directories.hosted_server_dir(server_id);
    let lines = read_lines(&server_dir).await?;
    let mut props = HostedServerProperties::default();

    for line in &lines {
        let RawLine::Entry { key, value } = line else {
            continue;
        };
        apply_entry(&mut props, key, value);
    }

    Ok(props)
}

/// Writes the given fields into `server.properties`, preserving every
/// other line (comments, unmanaged keys) exactly as-is. Creates the file
/// (with just the managed keys) if it doesn't exist yet.
pub async fn set(
    server_id: &str,
    props: &HostedServerProperties,
    state: &State,
) -> crate::Result<()> {
    let server_dir = state.directories.hosted_server_dir(server_id);
    let mut lines = read_lines(&server_dir).await?;

    let mut remaining = managed_entries(props);
    for line in &mut lines {
        let RawLine::Entry { key, value } = line else {
            continue;
        };
        if let Some(new_value) = remaining.remove(key.as_str()) {
            *value = new_value;
        }
    }

    // Any managed key that wasn't already present in the file gets
    // appended -- this is what makes `set` work even before the server has
    // ever generated its own `server.properties`.
    for (key, value) in remaining {
        lines.push(RawLine::Entry {
            key: key.to_string(),
            value,
        });
    }

    write_lines(&server_dir, &lines).await
}

/// Writes a starter `server.properties` (if one doesn't already exist) with
/// our own defaults right after a server finishes installing, so the port
/// setting takes effect on the very first launch and the settings panel
/// has something real to edit before the server has ever run.
pub async fn write_default_properties(
    server: &HostedServer,
    state: &State,
) -> crate::Result<()> {
    let server_dir = state.directories.hosted_server_dir(&server.id);
    if properties_path(&server_dir).exists() {
        return Ok(());
    }

    let props = HostedServerProperties::default();
    let mut lines = managed_entries(&props)
        .into_iter()
        .map(|(key, value)| RawLine::Entry {
            key: key.to_string(),
            value,
        })
        .collect::<Vec<_>>();
    lines.push(RawLine::Entry {
        key: "server-port".to_string(),
        value: server.port.to_string(),
    });

    write_lines(&server_dir, &lines).await
}

/// Keeps `server.properties`' `server-port` in sync when the port setting
/// changes, so it actually takes effect on the server's next launch instead
/// of silently doing nothing (as it did before this existed).
pub async fn set_port(server_id: &str, port: u16, state: &State) -> crate::Result<()> {
    let server_dir = state.directories.hosted_server_dir(server_id);
    let mut lines = read_lines(&server_dir).await?;
    let mut found = false;
    for line in &mut lines {
        if let RawLine::Entry { key, value } = line
            && key == "server-port"
        {
            *value = port.to_string();
            found = true;
        }
    }
    if !found {
        lines.push(RawLine::Entry {
            key: "server-port".to_string(),
            value: port.to_string(),
        });
    }
    write_lines(&server_dir, &lines).await
}

fn managed_entries(props: &HostedServerProperties) -> std::collections::HashMap<&'static str, String> {
    std::collections::HashMap::from([
        ("motd", props.motd.clone()),
        ("max-players", props.max_players.to_string()),
        ("difficulty", props.difficulty.clone()),
        ("gamemode", props.gamemode.clone()),
        ("hardcore", props.hardcore.to_string()),
        ("pvp", props.pvp.to_string()),
        ("online-mode", props.online_mode.to_string()),
        ("white-list", props.white_list.to_string()),
        ("enable-command-block", props.enable_command_block.to_string()),
        ("allow-flight", props.allow_flight.to_string()),
        ("allow-nether", props.allow_nether.to_string()),
        ("spawn-protection", props.spawn_protection.to_string()),
        ("view-distance", props.view_distance.to_string()),
        ("simulation-distance", props.simulation_distance.to_string()),
    ])
}

fn apply_entry(props: &mut HostedServerProperties, key: &str, value: &str) {
    match key {
        "motd" => props.motd = value.to_string(),
        "max-players" => {
            if let Ok(v) = value.parse() {
                props.max_players = v;
            }
        }
        "difficulty" => props.difficulty = value.to_string(),
        "gamemode" => props.gamemode = value.to_string(),
        "hardcore" => props.hardcore = value == "true",
        "pvp" => props.pvp = value == "true",
        "online-mode" => props.online_mode = value == "true",
        "white-list" => props.white_list = value == "true",
        "enable-command-block" => props.enable_command_block = value == "true",
        "allow-flight" => props.allow_flight = value == "true",
        "allow-nether" => props.allow_nether = value == "true",
        "spawn-protection" => {
            if let Ok(v) = value.parse() {
                props.spawn_protection = v;
            }
        }
        "view-distance" => {
            if let Ok(v) = value.parse() {
                props.view_distance = v;
            }
        }
        "simulation-distance" => {
            if let Ok(v) = value.parse() {
                props.simulation_distance = v;
            }
        }
        _ => {}
    }
}

async fn read_lines(server_dir: &Path) -> crate::Result<Vec<RawLine>> {
    let path = properties_path(server_dir);
    let contents = match io::read(&path).await {
        Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
        Err(_) => return Ok(Vec::new()),
    };

    Ok(contents
        .lines()
        .map(|line| {
            if !line.trim_start().starts_with('#')
                && let Some((key, value)) = line.split_once('=')
            {
                RawLine::Entry {
                    key: key.trim().to_string(),
                    value: value.to_string(),
                }
            } else {
                RawLine::Verbatim(line.to_string())
            }
        })
        .collect())
}

async fn write_lines(server_dir: &Path, lines: &[RawLine]) -> crate::Result<()> {
    io::create_dir_all(server_dir).await?;
    let mut contents = String::new();
    for line in lines {
        match line {
            RawLine::Entry { key, value } => {
                contents.push_str(key);
                contents.push('=');
                contents.push_str(value);
            }
            RawLine::Verbatim(raw) => contents.push_str(raw),
        }
        contents.push('\n');
    }
    io::write(properties_path(server_dir), contents.as_bytes()).await?;
    Ok(())
}
